# Generated by Django 4.1.7 on 2024-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='en_carrito',
            field=models.BooleanField(default=True),
        ),
    ]
