# Generated by Django 4.1.7 on 2024-05-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_remove_pedido_pagado_boleta_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='buy_order',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
