# Generated by Django 4.1.7 on 2024-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
