# Generated by Django 4.1.7 on 2024-05-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
