# Generated by Django 4.1.7 on 2024-07-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ciudad',
        ),
    ]
