# Generated by Django 4.1.7 on 2024-07-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_alter_factura_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='boleta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='back.boleta'),
        ),
    ]
