# Generated by Django 4.1.7 on 2024-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='direccion2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
