# Generated by Django 4.1.7 on 2024-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_alter_factura_direccion2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='direccion2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
